# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: Appdome

trigger:
- main

# pool:
#   vmImage: ubuntu-latest

steps:
- script: 
   echo $(System.DefaultWorkingDirectory);
   ls $(System.DefaultWorkingDirectory);
   ls $(Build.ArtifactStagingDirectory);
   ls $(System.ArtifactsDirectory);

- task: DownloadSecureFile@1
  name: App
  displayName: 'Download App'
  inputs:
    secureFile: 'TimeCard.apk'

- task: DownloadSecureFile@1
  name: keystore
  displayName: 'Download Keystore'
  inputs:
    secureFile: 'appdome.keystore'
- task: AndroidSign@0
  inputs:
    App: '$(App.secureFilePath)'
    Token: '$(Token)'
    FusionSetId: '$(Android_fusion_set)'
    KeystoreFile: '$(keystore.secureFilePath)'
    KeystorePass: 'appdome'
    KeystoreAlias: 'appdome'
    KeyPass: 'appdome'

# - task: AndroidPrivateSign@0
#   inputs:
#     App: '$(App.secureFilePath)'
#     Token: '$(Token)'
#     FusionSetId: '$(Android_fusion_set)'
#     SigningFingerprint: '$(Signing_fingerprint)'

