# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: Appdome

trigger:
- main

# pool:
#   vmImage: ubuntu-latest

steps:
- script: 
   echo $(System.DefaultWorkingDirectory);

- task: DownloadSecureFile@1
  name: App
  displayName: 'Download secure file'
  inputs:
    secureFile: 'TimeCard.apk'

# - task: DownloadSecureFile@1
#   name: mySecureFile1
#   displayName: 'Download secure file'
#   inputs:
#     secureFile: 'txt1.txt'

# - task: AndroidPrivateSign@0
#   inputs:
#       App: '$(App.secureFilePath)'
#       Token: '$(Token)'
#       FusionSetId: '$(Android_fusion_set)'
#       SigningFingerprint: '$(Signing_fingerprint)'