# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: Appdome

trigger:
- main

# pool:
#   vmImage: ubuntu-latest

steps:
- script: 
   echo $(System.DefaultWorkingDirectory);
   ls $(System.DefaultWorkingDirectory);
   ls $(Build.ArtifactStagingDirectory);
  #  cat /home/vsts/work/_tasks/AndroidSign_8c784d13-087d-4efd-89de-d80d500cb220/0.1.2/index.js;

- task: DownloadSecureFile@1
  name: App
  displayName: 'Download App'
  inputs:
    secureFile: 'TimeCard.apk'

- task: DownloadSecureFile@1
  name: keystore
  displayName: 'Download Keystore'
  inputs:
    secureFile: 'appdome.keystore'
- task: AndroidPrivateSign@0
  inputs:
    App: '$(App.secureFilePath)'
    Token: '$(Token)'
    FusionSetId: '$(Android_fusion_set)'
    SigningFingerprint: '$(Signing_fingerprint)'
# - task: AndroidSign@0
#   inputs:
#     App: '$(App.secureFilePath)'
#     Token: '$(Token)'
#     FusionSetId: '$(Android_fusion_set)'
#     KeystoreFile: '$(keystore.secureFilePath)'
#     KeystorePass: 'appdome'
#     KeystoreAlias: 'appdome'
#     KeyPass: 'appdome'



