# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# pool:
  # vmImage: ubuntu-latest

steps:
- script: 
#     ls "/home/vsts/work/_tasks/AppdomeAPI_badcce77-7016-461b-a6ee-8b911cdb7925/0.1.0/";
#     echo "---------------------------------------------------";
    cat "/home/vsts/work/_tasks/AppdomeAPI_badcce77-7016-461b-a6ee-8b911cdb7925/0.1.0/task.json";
#     echo "---------------------------------------------------";
#     ls "/home/vsts/work/_tasks/";


- task: DownloadSecureFile@1
  name: mySecureFile
  displayName: 'Download secure file'
  inputs:
    secureFile: 'txt.txt'

- task: DownloadSecureFile@1
  name: mySecureFile1
  displayName: 'Download secure file'
  inputs:
    secureFile: 'txt1.txt'
- task: AppdomeAPI1@0
  inputs:
    samplestring: 'dsdsada'
    fileInput: '$(mySecureFile. secureFilePath)'
- task: AppdomeAPI@0
  inputs:
    samplestring: 'csacsacs'
