trigger:
- main


steps:

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'appdome.keystore'
  name: keystore

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'FileFinder.aab'
  name: app

- task: Build-2Secure@0
  inputs:
    App: "$(app.secureFilePath)"
    FusionSetId: "4d9c60f0-1efc-11ee-b791-733894ee57f4"
    Token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYmZkNGM2ZTAtMWJmZS0xMWVlLWJhMGQtNDFlOGUzNWUzMGRjIiwic2FsdCI6IjYzZGQ0ZjhlLWJiYjktNGNlZC1iZjY0LTJjYjI5NTUyZWViNCJ9.elExsNJ6KOmfv9j8MbnNpsoUWqdAcDkOgOp9poQtnuI"
    Platform: 'android'
    Sign: 'signOnAppdome'
    KeystoreFile: "$(keystore.secureFilePath)"
    KeystorePass: 'appdome'
    KeystoreAlias: 'appdome'
    KeyPass: 'appdome'
    BuildWithLogs: true
    SecondOutput: true
    BuildToTest: 'lambdatest'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Appdome Output'


- script: |
   echo "Built APK file: $(buildTask.AppdomeSecuredApp)"
