# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: Appdome

trigger:
- bla

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo "##vso[task.setvariable variable=aaaa]12";
  displayName: 'Upload and Build none protected application'
 
- script: 
    echo $aaaa;
