# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: Appdome

trigger:
- main

# pool:
#   vmImage: ubuntu-latest

steps:


- task: DownloadSecureFile@1
  name: App
  displayName: 'Download App'
  inputs:
    secureFile: 'TimeCard.apk'

- script: 
   cat /home/vsts/work/_tasks/Build2Secure_0921a031-f037-4ad2-97bd-7d4abde94efa/0.1.2/index.js;
   ls /home/vsts/work/_tasks/Build2Secure_0921a031-f037-4ad2-97bd-7d4abde94efa/0.1.2/
# - task: DownloadSecureFile@1
#   name: keystore
#   displayName: 'Download Keystore'
#   inputs:
#     secureFile: 'appdome.keystore'
- task: DownloadSecureFile@1
  name: prov_profile
  displayName: 'Download Mobileprovision'
  inputs:
    secureFile: 'APPDOME_ALL.mobileprovision'

# - task: Build2Secure@0
#   inputs:
#     Platform: 'android'
#     Sign: 'privateSigning'
#     App: 'TimeCard.apk'
#     Token: '$(Token)'
#     FusionSetId: '$(Android_fusion_set)'
#     SigningFingerprint: '$(Signing_fingerprint)'
- task: Build2Secure@0
  inputs:
    Platform: 'ios'
    Sign: 'privateSigning'
    App: 'ARandomNumber.ipa'
    Token: '$(Token)'
    FusionSetId: '$(ios_fusion_set)'
    ProvisioningProfile: '$(prov_profile.secureFilePath)'
# - task: Build2Secure@0
#   inputs:
#     Platform: 'android'
#     Sign: 'signOnAppdome'
#     App: '$(App.secureFilePath)'
#     Token: '$(Token)'
#     FusionSetId: '$(Android_fusion_set)'
#     KeystoreFile: '$(keystore.secureFilePath)'
#     KeystorePass: 'appdome'
#     KeystoreAlias: 'appdome'
#     KeyPass: 'appdome'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'