# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: Appdome

trigger:
- main

# pool:
#   vmImage: ubuntu-latest

steps:
- script: 
   ls $(System.DefaultWorkingDirectory)/TimeCard.apk;
   

# - task: DownloadSecureFile@1
#   name: App
#   displayName: 'Download App'
#   inputs:
#     secureFile: 'TimeCard.apk'

- task: DownloadSecureFile@1
  name: keystore
  displayName: 'Download Keystore'
  inputs:
    secureFile: 'appdome.keystore'

# - task: Build2Secure@0
#   inputs:
#     Platform: 'android'
#     Sign: 'privateSigning'
#     App: 'TimeCard.apk'
#     Token: '$(Token)'
#     FusionSetId: '$(Android_fusion_set)'
#     SigningFingerprint: '$(Signing_fingerprint)'

# - task: Build2Secure@0
#   inputs:
#     Platform: 'android'
#     Sign: 'signOnAppdome'
#     App: "$(System.DefaultWorkingDirectory)/TimeCard.apk"
#     Token: '$(Token)'
#     FusionSetId: '$(Android_fusion_set)'
#     KeystoreFile: '$(keystore.secureFilePath)'
#     KeystorePass: 'appdome'
#     KeystoreAlias: 'appdome'
#     KeyPass: 'appdome'
# - task: PublishBuildArtifacts@1
  # inputs:
  #   PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  #   ArtifactName: 'drop'
  #   publishLocation: 'Container'