# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: Appdome

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
   echo $(Token);
   echo $(Android_fusion_set);
   publicLink=$(curl -s --request GET --url "https://fusion.appdome.com/api/v1/upload-link" --header "Authorization: $(Token)");
   echo $publicLink;
   curl -s -X PUT "$(echo "$publicLink" | jq -r .url)" --header 'Content-Type: application/x-compressed-tar' -T "TimeCard.apk";
   app=$(curl -s --request POST --url "https://fusion.appdome.com/api/v1/upload-using-link" --header "Authorization: $(Token)" --header 'content-type: multipart/form-data' \
              --form file_name="TimeCard.apk" --form file_app_id="$(echo "$publicLink" | jq -r .file_id)");
  displayName: 'Upload none protected application to Appdome'

- script: |
    task_id=$(curl -s --request POST --url "https://fusion.appdome.com/api/v1/tasks"  --header "Authorization: $(Token)" \
    --header 'accept: application/json' --header 'content-type: multipart/form-data' \
    --form action=fuse --form fusion_set_id="$(Android_fusion_set)" --form app_id="$(echo "$app" | jq -r .id)");
    task_id="$(echo "$task_id" | jq -r .task_id)";
    echo "task-id: $task_id";
  displayName: 'Buid none protected application on Appdome fusion platform'