# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: Appdome

trigger:
- main

# pool:
#   vmImage: ubuntu-latest

steps:
- script: 
    echo $(Token)
    echo $(Android_fusion_set)

# - task: DownloadSecureFile@1
#   name: mySecureFile
#   displayName: 'Download secure file'
#   inputs:
#     secureFile: 'txt.txt'

# - task: DownloadSecureFile@1
#   name: mySecureFile1
#   displayName: 'Download secure file'
#   inputs:
#     secureFile: 'txt1.txt'
