name: APPDOME_CI_EXAMPLE
# Controls when the workflow will run
on:
 # Triggers the workflow on push or pull request events but only for the "main" branch
 push:
  branches: [ "main" ]
 pull_request:
  branches: [ "main" ]
 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "build"
 a:
 # The type of runner that the job will run on
  runs-on: ubuntu-latest
 # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
   - uses: actions/checkout@v3
   - name: Appdome build-2secure
  # You may pin to the exact commit or the version.
  # uses: Appdome/github_build-2secure@85e6359e54cc2eee60d66a599fd37c0ee15f70dd
     uses: Appdome/github_build-2secure@1.1.2
     with:
       APPDOME_API_TOKEN: ${{secrets.APPDOME_API_KEY}}
       APP_FILE: "./FileFinder.aab"
       FUSION_SET_ID:  ${{secrets.APPDOME_FUSION_SET}}
       SIGN_OPTIONS: "SIGN_ON_APPDOME"
       KEYSTORE_FILE: "https://appdome-automation-vanilla-apps.s3.eu-central-1.amazonaws.com/Thomas/appdome.keystore?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEKn%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDGV1LWNlbnRyYWwtMSJHMEUCICr61XtXb5cZ9OcKQXO51kLvE7zpQ%2BJCUmTHf0t%2FXZQ4AiEAyYHsLDqhMdgolsBthO8X7SK5g3UkNXfvpe%2BNPW%2Bfg9EqhQMIQhAAGgwzMDIyNjc2NTQzOTQiDOHVvPrwzwIn%2FzFIWSriAsWAeC127Yz7BWrorWzSRwx3NnCqSZq5EiMYR1fAuk5QLP7Owf5LaqiwsMYu3F%2FLprs6B60P3DBuSjl0cIa1rPbV3ulA4ti%2BvXR3xj%2FIFRYQQdpqoO%2F%2BNE50s5hq%2BRZLKa5A6NjlbQ8g4xWuOEDQAGdkPig4vr5PSGn%2BxcCq77s6NmX3LMLJjFz0xenDrAZpFEQxZwoc1iwaHGUrlmG9wtk2wDv82e4GVvuWKRZRtq4oXV1aLlRpnG2RYnOGbH%2FkKLbUguulAPdlr4kpeTK40bS31T2djUWX%2Fkv9K19UUplp5Bny4p1ylFaDccWxH%2BAFkEcSg8pzfrj%2FnBKW3WM8UpLC0aeouLZIPJkC78mQZG3is88YHdFNKBKAxfYosLWM%2BuzbT94KH%2BWNytCgj7gwoB%2BU30MPkrARHP3DMHeQ8XnR61EnHKqLvm8pHO7wjkMLnll5t%2F%2BYmCXzMms8lscqG1i07zDOxYOmBjqzAmpHg728Vqg%2FmQgaTtDU2nrutZyVCyREHdjT6uJ287Nz%2Bh%2FDrXxjIJm3A0FDZalp0RNxoRonbf6C1PZ7cybrPt5ByBBEjJETAT4qRkVac8%2Ff2rip3x5Xy%2FuppBhAJBe%2BnSf5n3hxAFQn2hgNn2ALu4wyAyb61jD%2F5vKe8GdcZ4QaYKHi29VufZTovg2jv5uKLTBkShQp6kaK03TTc%2BSxsiiq9sBrkKEr6NGl%2FRAE8Hvp3usT51NZFxWgsY965hJIU9eiN8W%2BETpr7TjjxxruVnB%2FQzabMlai5x8QVtoi5EDlOYWwTAY3qHVzDMA5vUqfr5rhibPKysaBQsD16i7W67u104DBe26ftfBli3v3bjxxgORhIKnKFkMcuSsbeB8ZmEyPbyrzFXr%2Bm9iIH1VCDb9RCuM%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230726T123558Z&X-Amz-SignedHeaders=host&X-Amz-Expires=18000&X-Amz-Credential=ASIAUMYEOMD5CEWS2K2R%2F20230726%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Signature=4fd2924039e31e79fe829c36f0e77933a7106cc8c10a06dea4b88ff881c242a4"
       SECOND_OUTPUT: true
       BUILD_TO_TEST: "saucelabs"
       KEYSTORE_PASSWORD: "appdome"
       KEYSTORE_ALIAS: "appdome"
       KEYSTORE_KEY_PASSWORD: "appdome"
    
   - name: Example of using Appdome secured app
     run: |
        echo ${{ env.APPDOME_SECURED_APP }}
        echo ${{ env.APPDOME_SECURED_APP_SECOND_OUTPUT }}

#    - name: Appdome build-2secure
#      id: appdome-build
#      uses: Appdome/github_build-2secure@1.0
#      with:
#         APP_FILE: "./TimeCard.apk"
#         FUSION_SET_ID:  ${{secrets.APPDOME_FUSION_SET}}
#         SIGN_OPTIONS: "PRIVATE_SIGNING"
#         APPDOME_API_TOKEN: ${{secrets.APPDOME_API_KEY}}
#         SIGN_FINGERPRINT: ${{secrets.APPDOME_SIGN_FINGERPRINT}}
#         BUILD_WITH_LOGS: true
