name: APPDOME_CI_EXAMPLE
# Controls when the workflow will run
on:
 # Triggers the workflow on push or pull request events but only for the "main" branch
 push:
  branches: [ "main" ]
 pull_request:
  branches: [ "main" ]
 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "build"
 a:
 # The type of runner that the job will run on
  runs-on: ubuntu-latest
 # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
   - uses: actions/checkout@v3
   - name: Appdome build-2secure
  # You may pin to the exact commit or the version.
     uses: Appdome/github_build-2secure@1.1.2
     with:
       APPDOME_API_TOKEN: ${{secrets.APPDOME_API_KEY}}
       APP_FILE: "./FileFinder.aab"
       SIGN_OPTIONS: "PRIVATE_SIGNING"

       # iOS
       # MOBILE_PROVISION_PROFILE_FILE: "./Automation.mobileprovision"
       # ENTITLEMENTS_FILE: "./AutomationEntitlements.plist"
       # KEYSTORE_FILE: "./AutomationCert.p12"
       # KEYSTORE_PASSWORD: "nf1101"
       # FUSION_SET_ID:  "7eeb3600-295f-11ee-8107-df185da8f11b"

       # Android
       # KEYSTORE_FILE: "./appdome.keystore"
       # KEYSTORE_PASSWORD: "appdome"
       # KEYSTORE_ALIAS: "appdome"
       # KEYSTORE_KEY_PASSWORD: "appdome"
       FUSION_SET_ID:  "7fafc440-1ff8-11ee-a1d0-854aee3efdaf"
       SIGN_FINGERPRINT: "8DF593C1B6EAA6EADADCE36831FE82B08CAC8D74"

       
#        SECOND_OUTPUT: true
#        BUILD_TO_TEST: "saucelabs"
       
       
   - name: Example of using Appdome secured app
     run: |
        echo ${{ env.APPDOME_SECURED_APP }}
        echo ${{ env.APPDOME_SECURED_APP_SECOND_OUTPUT }}

#    - name: Appdome build-2secure
#      id: appdome-build
#      uses: Appdome/github_build-2secure@1.0
#      with:
#         APP_FILE: "./TimeCard.apk"
#         FUSION_SET_ID:  ${{secrets.APPDOME_FUSION_SET}}
#         SIGN_OPTIONS: "PRIVATE_SIGNING"
#         APPDOME_API_TOKEN: ${{secrets.APPDOME_API_KEY}}
#         SIGN_FINGERPRINT: ${{secrets.APPDOME_SIGN_FINGERPRINT}}
#         BUILD_WITH_LOGS: true
