name: APPDOME_CI_EXAMPLE
# Controls when the workflow will run
on:
 # Triggers the workflow on push or pull request events but only for the "main" branch
 push:
  branches: [ "main" ]
 pull_request:
  branches: [ "main" ]
 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "build"
 a:
 # The type of runner that the job will run on
  runs-on: macos-latest
 # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
   - uses: actions/checkout@v3
   - name: Appdome build-2secure
  # You may pin to the exact commit or the version.
     uses: Appdome/github_build-2secure@1.1.4
     with:
       APPDOME_API_TOKEN: ${{secrets.APPDOME_API_KEY}}
       SIGN_OPTIONS: "SIGN_ON_APPDOME"


       # iOS
       # APP_FILE: "./ARandomNumber.ipa"
       # MOBILE_PROVISION_PROFILE_FILE: "./Automation.mobileprovision"
       # ENTITLEMENTS_FILE: "./AutomationEntitlements.plist"
       # KEYSTORE_FILE: "./AutomationCert.p12"
       # KEYSTORE_PASSWORD: "nf1101"
       # FUSION_SET_ID:  "7eeb3600-295f-11ee-8107-df185da8f11b"

       # Android
       APP_FILE: "./FileFinder.aab"
       KEYSTORE_FILE: "https://appdome-automation-vanilla-apps.s3.eu-central-1.amazonaws.com/Thomas/appdome.keystore?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGIaDGV1LWNlbnRyYWwtMSJHMEUCIBatyYGLURmNHbE0UTf9xH2nzEp%2BKnVnEARivYGu%2FLczAiEAi%2BH9YtqDJbCE2IIA8Dl%2Fppb36OY0EjTG2P5Yn6iBMg0qhQMIKxAAGgwzMDIyNjc2NTQzOTQiDA3ddzgslsSt0uxHhSriAmCj1jr%2Fp8pyc2F%2BqIki4wZ%2FxmLBtrNzRUHRmL%2B%2FoFvvsIOrUYOUj1DjX0PU%2FVtNamKUNAwp0N2YPkjJAZWfHhFcVqv%2BHwtkVbF7VvsBdb6OiFrpcvoYEskdQvrIPTTZNb2%2FqCB3r8XnFB04vsHajMRGGG9xgJpQ9rtrzKVPCsY45fNwIgMpi%2FtgOh%2BnbYs1kiYBlaUJv%2B%2BDK6v1NjKO6KbtLIwi95e%2F6ofFWt%2BeoQY%2FdTQZoRtR4trekxnwnMqWhIGsDWC7jPjKhivgTrXzZ9r3Gt3u7b4IgZKgHF3lqL6DlcNSVQIF6WYt%2BpjWu17tKcNaJOcDY1zSuXt3RP39nI7QOvedsaJvuYW1NhNdwMduzbkk0w7EqdfjMUe2496UMCStNAalQ6YvxA9sqDrvfZwVko5%2BwpbcDZFtp%2BMJWuVK406n9mJWy1W6diHPyH8pelW7wqlzM%2FKIebq9KU2I0%2FGIYDCEzZynBjqzAiaAx%2FxHSbbbm0Lcb4VfJRZLvQqfwFZYU4CDtDTZphzx89vOt2%2BCBlTHFK7jyTfISdW%2BWZptN5DoVl3gbbi8WRisWuT6XOeI7Z1oFqvsD0txXGu8VgXRsVenziVFjhmuXjzsQHLL7VHnJDBOBtBO3062Ak6s7PwH%2BGm%2Bp55JOv7aZ3CdvWgrGEzzz53ahT10qjkP1oYzsu5nt0avqMYOJMCR2IZNr6VwZD2LtHKpnc6sN85%2FAdXJQ%2FWMgelUQdHNIcklUbnXFsQropA2eWZ9OU3lXOsFVRp8cHFo5uoGHEZNENbXgWzdgVHnv%2B9wddCyLYFYrUIZ60gIhfqyaU0SwFzHo0bDZ8iNkHdR1geGtZbmJ2RvMkE1C0o6AhdDtm0xo3cZUjSJ%2BWzN4s%2FmlUrlqoJ37g4%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230824T140527Z&X-Amz-SignedHeaders=host&X-Amz-Expires=18000&X-Amz-Credential=ASIAUMYEOMD5KJBDCEB3%2F20230824%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Signature=94ac85115a4a67c73e19d9d001b7293bae68fb24590b2985916c285d7b13bc5e"
       KEYSTORE_PASSWORD: "appdome"
       KEYSTORE_ALIAS: "appdome"
       KEYSTORE_KEY_PASSWORD: "appdome"
       FUSION_SET_ID:  "7fafc440-1ff8-11ee-a1d0-854aee3efdaf"
       # SIGN_FINGERPRINT: "8DF593C1B6EAA6EADADCE36831FE82B08CAC8D74"

#        SECOND_OUTPUT: true
#        BUILD_TO_TEST: "saucelabs"
       
   - name: Example of using Appdome secured app
     run: |
        echo ${{ env.APPDOME_SECURED_APP }}
        echo ${{ env.APPDOME_SECURED_APP_SECOND_OUTPUT }}

