name: APPDOME_CI_EXAMPLE
# Controls when the workflow will run
on:
 # Triggers the workflow on push or pull request events but only for the "main" branch
 push:
  branches: [ "github" ]
 pull_request:
  branches: [ "github" ]
 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "build"
 a:
 # The type of runner that the job will run on
  runs-on: ubuntu-latest
 # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
   - uses: actions/checkout@v3
   - name: Appdome build-2secure
  # You may pin to the exact commit or the version.
     uses: Appdome/github_build-2secure@1.3.0
     with:
       APPDOME_API_TOKEN: ${{secrets.APPDOME_API_KEY}}
       SIGN_OPTIONS: "PRIVATE_SIGNING"
       

       # iOS
       # APP_FILE: "./ARandomNumber.ipa"
       # MOBILE_PROVISION_PROFILE_FILE: "./Automation.mobileprovision"
       # ENTITLEMENTS_FILE: "./AutomationEntitlements.plist"
       # KEYSTORE_FILE: "./AutomationCert.p12"
       # CERTIFICATE_PASSWORD: "nf1101"
       # FUSION_SET_ID:  "dd6b1360-5864-11ee-96fa-bb616f57e574"

       # Android
       APP_FILE: "https://appdome-automation-vanilla-apps.s3.eu-central-1.amazonaws.com/Thomas/CitiManager.apk?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjECYaDGV1LWNlbnRyYWwtMSJGMEQCIBD9R8aEWe7%2BLamzs1eGtJczizgXZOqfIas7yEFt%2Bl0sAiA%2BDP3Y8PkZ%2BxqYbuj775IWfbjnD88IHZdkBhkpzi50YCqBAwgvEAAaDDMwMjI2NzY1NDM5NCIMtbSvTY16aqM%2Bn3FIKt4Cce0SkSWNfzdDs3LxnoTMG5gLJFbnI6XNyENtKj8K3v%2B8oKMKCRrnDB2f5GYxDaviON6LrmyHCeZaT2bWUT7VxrD0T5t%2F7l0HTajpk8Q1KUMbjYR3WWbio%2FdSZtQ%2F5Kv3ryYGVPehlsDP2gzA7iMLGxtd8OxmemEnRGJtBrww%2Be62MUhYTZz5t13WIlyuBNK5nn7VNVBqVuCNOgoBHKKI%2B8q6jEi%2FbpHsmHWUe3WGtISdrHEHIIh8wm4YUAPSB3BnXeHNn2%2FTG5nC3WZsDa4Fwt9w0EAXi9PQ%2F8Wt3%2Bz6Uwn4ubwqppaDJcB93XMEs60f7L%2BmAt9jtq78GgGAlPh6akSbJZ4LSlqgg3gxWYJQ3YLKWRE7vooPSqENZxl5kHWstqKtPLdKvVD%2F7msm%2ByoH0VlW6bzyW1iPtlcfLuEMMN%2F8cS2x0XkC%2BuKgDwlTWeX8y8ycbLunUHu%2BDZ4bw6cwkLbwqAY6tAL2yWmYBcUjcLRfCzK%2FPfsNZG6mocY%2FGuy%2F4xYoNxihlE7YxvTd107or0vc9DIdr7xPJnArJT3AUWV33fWbCOeB%2FC2F%2BIdRfX60TqGWiCViC1p7bznCrd6CKQCGU0eGhYUpbRDzx9cpCvVhAVq0fKfqVg9glrBdcGw9fD%2FeXlzXugU9Tx0xWLZgpre%2FuwSVd6QKJJAUfN%2Bp%2FslSayQkfWk%2BlCwWuFumQn5RiFk1BirvjOYHtJmheR8A5V1wcfmtoxQY4N3J2NT5BnJCsf1GLv0xehb%2BHwjZvc39IPh3BPGqvwgM2aF8J7%2F5QlwaNfKkgL9g0CyNTfvChtTUbQqgNJyXibRB9AxcFRPNm5C6XuDYDqPEncjQab3qnVdsKjBRogVx19IyAbzAh4ty3zN5ZYdZ4tyf0Q%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231003T135443Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIAUMYEOMD5ISN4UWBT%2F20231003%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Signature=43282530b8b41a1daf89f1c7cf930ae8655c23f634de910ff76f8ceb1f220bcb"
       # KEYSTORE_FILE: "./appdome.keystore"
       # KEYSTORE_PASSWORD: "appdome"
       # KEYSTORE_ALIAS: "appdome"
       # KEYSTORE_KEY_PASSWORD: "appdome"
       FUSION_SET_ID:  "d2574330-5856-11ee-800b-a111bd4d22d3"
       SIGN_FINGERPRINT: "8DF593C1B6EAA6EADADCE36831FE82B08CAC8D74"

       # SECOND_OUTPUT: true
       OUTPUT_APP_NAME: "test/test_app.apk"
#        BUILD_TO_TEST: "saucelabs"
       
   - name: Example of using Appdome secured app
     run: |
        echo ${{ env.APPDOME_SECURED_APP }}
        echo ${{ env.APPDOME_SECURED_APP_SECOND_OUTPUT }}

